### ISSUE TITLE
feat(plugin): Repost to another channel via Reaction

### ISSUE THREAD

**Issue by perzeuss** [mavolin/stormy#1]
### Motivation and Description
Lets say, you want to manage multiple channels e.g. one for feature suggestions and one with accepted ones. It would be nice, if the bot could handle an emoji reaction on an existing message (e.g. one in the "suggestions" channel) and repost its content to another channel (e.g. "approved").

That would help people to organize suggestions.

### Few Ideas for Development:

- Emoji, that triggers the channel move, can be configured
- `config.plugin.repost.channels` object, with source-target (key-value), can be configured. This would support multiple channel use. Example:  `{"ch1":"ch2", "ch3":"ch5"}` "reaction in ch1 moves message to ch2". "reaction in ch3 moves message to ch5"
- `config.plugin.repost.rights` object with arrays for user and role IDs that can use this reaction. Example: {"users":  ["123", "234"], "roles": ["321", "423"]}

**Comment by mavolin** [comment]
What should happen, if the user removes his reaction again?
Should the crossposted message be removed, or should it stay?

**Comment by perzeuss** [comment]
> What should happen, if the user removes his reaction again?
> Should the crossposted message be removed, or should it stay?

It should stay, I'd suggest to always remove the user reaction immediately. Handling 'un-react' isn't stable.

**Comment by mavolin** [comment]
Agreed.
